"use strict";

const mongoose = require("mongoose");
const common = require("./_common");

/**
 * AudioEvent
 * - Represents an audio-related event generated by a device/car.
 * - Links to AudioMetadata when a file is uploaded.
 */
const AudioEventSchema = new mongoose.Schema(
  {
    carId: { type: String, required: true },
    deviceId: { type: String, required: true },
    eventType: { type: String, required: true },
    location: { type: String, required: false },
    audioMetadataId: { type: mongoose.Schema.Types.ObjectId, ref: "AudioMetadata", required: false },
    alertGenerated: { type: Boolean, default: false },
    processed: { type: Boolean, default: false },
    timestamp: { type: Date, required: true },
  },
  common
);

AudioEventSchema.index({ carId: 1, timestamp: -1 });
AudioEventSchema.index({ deviceId: 1, timestamp: -1 });
AudioEventSchema.index({ eventType: 1, timestamp: -1 });

module.exports = mongoose.model("AudioEvent", AudioEventSchema, "audio_events");

